# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf86edc0991bf75b14d362e4508737963a5b9176939fa4a41bb17c34a6dd8af0e077ece2e74abdd30ea1b4f6f7ca9e1041e24c8d9601133ea9cc67a2bad1bea7

test:
  secret_key_base: 2e79b86ea510bc171aaa3aa6045034cd52744154d598236a79d77209151cfe746f26c7631cb7a392154ed5f97c82c602c93388bddacb0a5515118716b443667e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
